### ISSUE TITLE
Loading form by URI rather than document

### ISSUE THREAD

**Issue by josephguillaume** [smessie/FormGenerator#4]
If I understand correctly, the code currently loads the first object with a form class found in the store

https://github.com/smessie/FormGenerator/blob/d03c2d67b6af90d93d3795f01360bebe86cf07b8/app/routes/index.js#L104

Loading a specific form (e.g. form.ttl#this) is not supported. In addition to not yet allowing editing of separate forms in a single document, this approach uses implicit rather than explicit semantics about what is in the document, which should be avoided: https://twitter.com/RubenVerborgh/status/1582357537864945665

**Comment by smessie** [comment]
This is now fixed in https://github.com/SolidLabResearch/FormGenerator/commit/ac889ccf7f235f40a6a5175a336465a11d4bbd6b.
