### ISSUE TITLE
"ember serve" doesn't work

### ISSUE THREAD

**Issue by pheyvaer** [smessie/FormGenerator#6]
When following the instructions `ember serve` doesn't work. I have to do `npx ember serve`.

**Comment by smessie** [comment]
Therefore you should install the Ember CLI via `npm install -g ember-cli`
More info on that on https://cli.emberjs.com/release/

**Comment by pheyvaer** [comment]
People might be reluctant to install dependencies globally just to try something out. But to be fair it's mentioned in the README that the CLI is required.

**Comment by smessie** [comment]
Fair enough, I've added the alternative instruction to the readme as well in https://github.com/smessie/FormGenerator/commit/5566d43008c66dda60054e2b088e648f39481a61
